title: "AO3 Work Skins by @wovenstarlight"
description: "Work skins created to style Archive Of Our Own works. Made by @wovenstarlight."
author: "wovenstarlight"
ao3_ws: https://archiveofourown.org/users/wovenstarlight/pseuds/wovenstarlight
ao3_ua: https://archiveofourown.org/users/wovenstarlight/pseuds/unpredictableArtist

domain: wovenstarlight.github.io
url: https://wovenstarlight.github.io
baseurl: /workskins

# Adding default layout and header file for non-post pages.
defaults:
  -
    scope:
      path: "" # all files in the project
    values:
      layout: "default"